### ISSUE TITLE
Doors reopen while player is stopped on green square in tutorial map

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#41]
https://files.facepunch.com/howie/1b0711b1/sbox-dev_14hSJ8nZhy.mp4

**Comment by cr4yz** [comment]
I've set it to keep the doors open while the player is stopped on the square and 4 seconds after the player moves the door will close.  Lemme know if that's okay!

**Comment by youhavehowie** [comment]
I think we can just leave doors open after the player has stopped for 1 sec or so on the square, if they close again after they open i think it might be confusing

**Comment by cr4yz** [comment]
Gotcha, should be fixed now

**Comment by youhavehowie** [comment]
so I triple checked to make sure i had everything pulled, main repo and maps repo :P, seems like after the doors open they still close after about 4 sec and then reopen if I'm stopped on the green square.

**Comment by cr4yz** [comment]
Ah, did you recompile uf_tutorial after pulling?  We aren't keeping vpks on git.  

Alternatively disabling uf_tutorial/unicycle frenzy in addon manager will make s&box download the latest live version rather than loading up the local copy: https://files.facepunch.com/crayz/1b1111b1/sbox-dev_2022-03-11_11-47-28.png

**Comment by youhavehowie** [comment]
yup that did it, sorry! Looks great
